<?php

/**
Pentagon numbers

Pentagonal numbers are generated by the formula, P_n = n(3n -1) / 2.  The first ten pentagonal
numbers are:

	1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8.  However, their difference, 70 - 22 = 48,
is not pentagonal.

Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal
and D = |P_k - P_j| is minimised; what is the value of D?
**/

$pents = array();
$pentsr = array();

for($i = 1; $i < 5000; $i++) {
	$p = pentagon($i);
	$pents[$i] = $p;
	$pentsr[$p] = $i;
}

function pentagon($n) {
	return $n * (3 * $n - 1) / 2;
}

for($i = 1; ; $i++) {
	$ip = $pents[$i];
for($j = 1; $j <= $i; $j++) {
	$jp = $pents[$j];
	$add = $ip + $jp;
	if(!isset($pentsr[$add])) continue;
	$diff = abs($jp - $ip);
	if(!isset($pentsr[$diff])) continue;

	print $i . " " . $j . ", " . $jp . " -  " . $ip . " = " . $diff . "\n";
	die();
}
}

?>

